/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BubbleChartComp: typeof import('./src/components/BubbleChartComp.vue')['default']
    ChatComp: typeof import('./src/components/ChatComp.vue')['default']
    ChinaMapComp: typeof import('./src/components/ChinaMapComp.vue')['default']
    DynastyComparisonChart: typeof import('./src/components/DynastyComparisonChart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    EmotionPieComp: typeof import('./src/components/EmotionPieComp.vue')['default']
    NavbarComp: typeof import('./src/components/NavbarComp.vue')['default']
    PersonalNetwork: typeof import('./src/components/PersonalNetwork.vue')['default']
    PersonalNetworkComp: typeof import('./src/components/PersonalNetworkComp.vue')['default']
    PieComp: typeof import('./src/components/PieComp.vue')['default']
    PoetCardComp: typeof import('./src/components/PoetCardComp.vue')['default']
    PoetSanKeyComp: typeof import('./src/components/PoetSanKeyComp.vue')['default']
    RadarComp: typeof import('./src/components/RadarComp.vue')['default']
    ReigonBarComp: typeof import('./src/components/ReigonBarComp.vue')['default']
    RelationGraphComp: typeof import('./src/components/RelationGraphComp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpecificCateTreemap: typeof import('./src/components/SpecificCateTreemap.vue')['default']
    SunBurstComp: typeof import('./src/components/SunBurstComp.vue')['default']
    TimelineScatterComp: typeof import('./src/components/TimelineScatterComp.vue')['default']
    WordCloudComp: typeof import('./src/components/WordCloudComp.vue')['default']
  }
}
